name: jarvis_app
description: A Flutter app to control Jarvis AI Assistant

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  cupertino_icons: ^1.0.2
  
  # HTTP and WebSocket communication
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  
  # Voice solution: Built-in keyboard voice input + TTS output (no problematic packages)
  flutter_tts: ^3.8.3
  
  # Audio streaming and playback
  audioplayers: ^6.0.0
  
  # URL launching for mobile control system
  url_launcher: ^6.1.12
  
  # State management
  provider: ^6.1.1
  
  # UI enhancements
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.3.0
  glass_kit: ^3.0.0
  
  # Date formatting
  intl: ^0.19.0
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets for JARVIS branding
  assets:
    - assets/images/ 